### ISSUE TITLE
Broken after OC 8.2

### ISSUE THREAD

**Issue by briskspirit** [icewind1991/logreader#10]
Hello. Just updated to 8.2 from 8.1.3 and now your app is broken... Just blank page and nothing else. Tried to reinstall app - no luck.

**Comment by Thomas830** [comment]
Hi,
I've just let a message on apps.owncloud.org but I'd rather should have done it here I guess.
Same problem here, here's the log:
`Error 	logreader 	Could not find resource file "/owncloud/apps/logreader/css/../build/main.css" 	2015-11-21T10:12:36+00:00`
`Error 	logreader 	Could not find resource file "/owncloud/apps/logreader/js/../build/main.js" 	2015-11-21T10:12:36+00:00 `

**Comment by bcutter** [comment]
Maybe it´s because you have "JavaScript and CSS Asset Management" activated in OwnCloud? I activated it using https://doc.owncloud.org/server/8.2/admin_manual/configuration_server/js_css_asset_management_configuration.html and everything worked fine - EXCEPT Logreader, which isn´t loaded anymore (white page). If i disable the 'asset-pipeline.enabled' in config.php Logreader works again.

I guess that´s the reason for the "It is not recommended to enable asset-pipelining when using apps pulled via git." on the official OC documentation (see link above).

Can you "make it work" with JS / CSS Asset Management? Only Logreader keeps me away from activating this performance setting!
