### ISSUE TITLE
Invalid date in Time column

### ISSUE THREAD

**Issue by tessus** [icewind1991/logreader#4]
I've installed LogReader 1.0.0 via the Apps (experimental) in ownCloud.

Every record states **Invalid date**.

I'm using PHP 5.6.12 and ownCloud 8.1.1. There are no entries in the owncloud.log and php error log pertaining this problem. The time entry in my owncloud log looks like this:

```
"time":"2015-08-29 03:14:17 +0200"
```

**Comment by tessus** [comment]
My server is located in Europe, thus the timezone +0200. But my client is in the timezone -0400.
I don't know how the date presentation is coded, but maybe this is the reason for the error.

**Comment by tessus** [comment]
@icewind1991 any idea why I get an `Invalid date`?

**Comment by cdamken** [comment]
@tessus 
Do you have in the log file the same wrong information?
Could you put your config.php?
Do you have configured:
```
 'logtimezone' => 'CEST',
```

I think is problem of your configuration and not from the app, the app only uses the information from your log.

**Comment by tessus** [comment]
Unfortunately, there are no errors in the owncloud.log nor the php error log.

My config re logging looks like this:

```
  'logdateformat' => 'Y-m-d H:i:s O',
  'logtimezone' => 'Europe/Vienna',
```

**Comment by icewind1991** [comment]
It relies on js's date parsing, what browser are you using?

**Comment by tessus** [comment]
I'm using Firefox, but I've also tested it with Safari. My client OS is Mac OS X 10.9.5.

**Comment by j-ed** [comment]
## Environment
#### Server Configuration
OS: Linux 3.2.67
Web server: Apache2 2.4.17
Database: MySQL 5.1.73
PHP version: 5.6.13
ownCloud version: 8.1.3

#### Client Configuration
Browser: Firefox 41.0.2
Operating system: Windows 7


"level":0,"time":"2015-10-12 00:13:03+02:00",
I can confirm that `Invalid date`is displayed in the log view.
This is the date format used in the log file: `... ,"time":"2015-10-12 00:13:03+02:00", ...`
 My configuration entries are as follows:
```
'logdateformat' => 'Y-m-d H:i:sP',
'logtimezone' => 'Europe/Berlin',
```
What else do you need to identify the root cause of the problem?

**Comment by icewind1991** [comment]
Ok, it seems firefox is more strict about it's date parsing then chrome, it expects `2015-10-12T00:13:03+02:00` instead (note the T between the date and time instead of a space)
